name: safeandsmooth
channels:
    - defaults
    - conda-forge
    - anaconda
dependencies:
    - python=3.10
    - pip=22.3

    - jupyter
    - seaborn>=0.12.2
    - numpy>=1.23.5
    - scipy>=1.9.0
    - pandas>=1.4.3
    - progressbar2==4.0
    - pyyaml>=6.0
    - pytest>=7.1.2
    - scikit-umfpack>=0.3.3
    - scikit-sparse>=0.4.8
    - pip:
      - -e poly_matrix
      - -e . 
